version: "3.4"
services:
  backend:
    build: .
    ports:
      - 8089:8089
    environment:
      - SERVER_PORT=8089
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1235
      POSTGRES_DB: lapka
    volumes:
      - type: bind
        source: ./pgdata
        target: /var/lib/postgresql/data
